### ISSUE TITLE
Error: stack level too deep appearing when trying to install formula

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/brew#434] opened 2017-07-19 16:58 UTC
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

*****

Hi. Hope this is the right forum to post to. 

I've been encountering a number of `Error: stack level too deep` messages coming from brew when running on Linux. I've not confirmed if this is just a linux thing or not but it happens with a number of formulas. The latest one was https://github.com/Ensembl/homebrew-cask/blob/master/eg-dna-features.rb. This is a meta formula and it's a total hack of the system but I use them to coordinate multiple package installations into brew. Anyway this is the output I got

```bash
$ brew install ensembl/cask/eg-dna-features
==> Installing eg-dna-features from ensembl/cask
Error: stack level too deep
/usr/share/ruby/pathname.rb:334
```

I commented out all dependencies apart from `homebrew/science/trf` and it installed the package. Bringing back any of the other `ensembl/ensembl` dependencies just brought with it the same message but now being raised from the `reinstall.rb` command

```bash
$ brew reinstall ensembl/cask/eg-dna-features
Error: stack level too deep
/nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/Library/Homebrew/cmd/reinstall.rb:55
```

I did some investigating and this error came from the `FormulaInstall.check_install_sanity` method but I don't know why. All I can think is that there's something going on with these formula that is sending a recursive loop going. However this is the tree dependency listings:

```bash
$ brew deps --tree ensembl/cask/eg-dna-features
ensembl/cask/eg-dna-features (required dependencies)
├── ensembl/ensembl/blast
│   ├── :mysql
│   ├── :python
│   ├── jpeg
│   ├── libpng
│   │   ├── xz
│   │   └── zlib
│   └── pcre
│       ├── bzip2
│       └── zlib
├── ensembl/ensembl/repeatmasker
│   ├── homebrew/science/hmmer
│   ├── ensembl/ensembl/rmblast
│   │   └── ensembl/ensembl/blast
│   │       ├── :mysql
│   │       ├── :python
│   │       ├── jpeg
│   │       ├── libpng
│   │       │   ├── xz
│   │       │   └── zlib
│   │       └── pcre
│   │           ├── bzip2
│   │           └── zlib
│   ├── homebrew/science/trf
│   ├── ensembl/moonshine/phrap
│   └── ensembl/moonshine/repbase
├── ensembl/ensembl/repeatmodeler
│   ├── homebrew/science/recon
│   ├── ensembl/ensembl/repeatmasker
│   │   ├── homebrew/science/hmmer
│   │   ├── ensembl/ensembl/rmblast
│   │   │   └── ensembl/ensembl/blast
│   │   │       ├── :mysql
│   │   │       ├── :python
│   │   │       ├── jpeg
│   │   │       ├── libpng
│   │   │       │   ├── xz
│   │   │       │   └── zlib
│   │   │       └── pcre
│   │   │           ├── bzip2
│   │   │           └── zlib
│   │   ├── homebrew/science/trf
│   │   ├── ensembl/moonshine/phrap
│   │   └── ensembl/moonshine/repbase
│   ├── homebrew/science/repeatscout
│   ├── ensembl/ensembl/rmblast
│   │   └── ensembl/ensembl/blast
│   │       ├── :mysql
│   │       ├── :python
│   │       ├── jpeg
│   │       ├── libpng
│   │       │   ├── xz
│   │       │   └── zlib
│   │       └── pcre
│   │           ├── bzip2
│   │           └── zlib
│   └── homebrew/science/trf
└── homebrew/science/trf
```

There's a bit of repetition in there but if I change the formula to just including `ensembl/ensembl/repeatmodeler` the error persists (so i don't think it's to do with that). 

I've included commonly asked for bits of information in here such as config, doctor and tap debug below. Hope you can help

Cheers.

*****

Config output:
```
HOMEBREW_VERSION: 1.2.4-2-g59a338502
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 59a33850248e81f2301c5e534a59a7d660ab3718
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: d8680a06496db855c369de3e9ba3cb93a360c270
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /nfs/software/ensembl/RHEL7-JUL2017/linuxbrew
HOMEBREW_REPOSITORY: /nfs/software/ensembl/RHEL7-JUL2017/linuxbrew
HOMEBREW_CELLAR: /nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 32-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p598 => /usr/bin/ruby
Clang: N/A
Git: 2.13.2 => /nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/bin/git
Perl: /usr/bin/perl
Python: /nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/bin/python => /nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_112
Kernel: Linux 3.10.0-327.18.2.el7.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 7.2 (Maipo) (Maipo)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.19
gcc: 5.3.0
xorg: 20170115
```

Doctor output:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /nfs/production/mpi/mpich/mpich3/3.1-intel//lib:/nfs/production/intelcc/composer_xe_2013.3.163//compiler/lib/intel64:/nfs/production/intelcc/composer_xe_2013.3.163//mpirt/lib/intel64:/nfs/production/intelcc/composer_xe_2013.3.163//ipp/lib/intel64:/nf
s/production/intelcc/composer_xe_2013.3.163//mkl/lib/intel64:/nfs/production/intelcc/composer_xe_2013.3.163//tbb/lib/intel64/gcc4.1

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /bin/nss-config
  /bin/nss-util-config
  /bin/Magick++-config
  /bin/krb5-config
  /bin/rarian-sk-config
  /bin/gdlib-config
  /bin/apr-1-config
  /bin/sane-config
  /bin/Magick-config
  /bin/pkg-config
  /bin/ncurses5-config
  /bin/python2-config
  /bin/libpng15-config
  /bin/ijs-config
  /bin/scrollkeeper-config
  /bin/MagickWand-config
  /bin/apu-1-config
  /bin/iokit-config
  /bin/libgnutls-config
  /bin/libpng-config
  /bin/xml2-config
  /bin/orbit2-config
  /bin/freetype-config
  /bin/pcre-config
  /bin/cups-config
  /bin/libusb-config
  /bin/gpg-error-config
  /bin/libgcrypt-config
  /bin/Wand-config
  /bin/nspr-config
  /bin/brltty-config
  /bin/kde4-config
  /bin/nss-softokn-config
  /bin/xslt-config
  /bin/net-snmp-config
  /bin/icu-config
  /bin/python-config
  /bin/libart2-config
  /bin/python2.7-config
  /bin/curl-config
  /bin/MagickCore-config
  /bin/gsl-config
  /bin/ncursesw5-config
  /sbin/pef-config
  /sbin/ipmi-chassis-config
  /sbin/netlabel-config
  /sbin/ipmi-pef-config
  /sbin/ipmi-sensors-config
  /sbin/bmc-config

Consider setting your PATH so that /nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/bin:$PATH"' >> ~/.bash_profile

Warning: Homebrew's bin was not found in your PATH.
Consider setting the PATH for example like so
  echo 'export PATH="/nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/bin:$PATH"' >> ~/.bash_profile

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/nfs/software/ensembl/RHEL7-JUL2017/linuxbrew/sbin:$PATH"' >> ~/.bash_profile
```

Brew tap (with `--debug`) output:
```
ensembl/ensembl
ensembl/moonshine
ensembl/cask
ensembl/icc
homebrew/core
homebrew/science
homebrew/dupes
homebrew/versions
linuxbrew/extra
linuxbrew/xorg
```

**Comment by sjackman** [comment] 2017-07-19 19:44
We're actively working on fixing this bug. We'll hopefully have a fix in a day or two. Sorry for the breakage. 🤕
Duplicate of https://github.com/Linuxbrew/brew/issues/430

**Closed as completed by sjackman** 2017-07-19 19:44 UTC
Labels: bug, duplicate

**Comment by andrewyatz** [comment] 2017-07-19 22:10
Sorry didn't check for other issues and thanks for looking into it.
