### ISSUE TITLE
I cannot install Linuxbrew on Ubuntu 16.04

### ISSUE THREAD

**Issue by adonese** [Linuxbrew/brew#195] opened 2016-12-04 07:23 UTC
When I try to do 
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"`
I got these errors
```
Error: Invalid formula: /home/adonese/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/internetarchive.rb
cannot load such file -- utils/json
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/adonese/.linuxbrew/bin/brew tap homebrew/core
```

**Comment by sjackman** [comment] 2016-12-04 18:54
Hi, Mohamed. Thanks for the bug report. This issue is a duplicate of #194 and will soon be resolved by https://github.com/Linuxbrew/homebrew-core/pull/1231. Sorry for the hassle.

**Closed as completed by sjackman** 2016-12-04 18:54 UTC
Labels: bug, duplicate
