### ISSUE TITLE
crystal install fails

### ISSUE THREAD

**Issue by jney** [Linuxbrew/brew#646] opened 2018-03-13 22:09 UTC
Installing crystal i've got this verbose, but explicit message

```
Last 15 lines from /home/jney/.cache/Homebrew/Logs/llvm@5/02.make:
cd /tmp/llvm@5-20180313-32135-1yumi5f/tools/lld/lib/ReaderWriter/MachO && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.10.2/bin/cmake -E cmake_link_script CMakeFiles/lldMachO.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/bin/ar qc ../../../../../lib/liblldMachO.a  CMakeFiles/lldMachO.dir/ArchHandler.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_arm.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_arm64.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_x86.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_x86_64.cpp.o CMakeFiles/lldMachO.dir/CompactUnwindPass.cpp.o CMakeFiles/lldMachO.dir/GOTPass.cpp.o CMakeFiles/lldMachO.dir/LayoutPass.cpp.o CMakeFiles/lldMachO.dir/MachOLinkingContext.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileBinaryReader.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileBinaryWriter.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileFromAtoms.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileToAtoms.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileYAML.cpp.o CMakeFiles/lldMachO.dir/ObjCPass.cpp.o CMakeFiles/lldMachO.dir/ShimPass.cpp.o CMakeFiles/lldMachO.dir/StubsPass.cpp.o CMakeFiles/lldMachO.dir/TLVPass.cpp.o CMakeFiles/lldMachO.dir/WriterMachO.cpp.o
/home/linuxbrew/.linuxbrew/bin/ranlib ../../../../../lib/liblldMachO.a
make[2]: Leaving directory '/tmp/llvm@5-20180313-32135-1yumi5f'
[ 15%] Built target lldMachO
[ 15%] Linking CXX static library ../../libLLVMDebugInfoPDB.a
cd /tmp/llvm@5-20180313-32135-1yumi5f/lib/DebugInfo/PDB && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.10.2/bin/cmake -P CMakeFiles/LLVMDebugInfoPDB.dir/cmake_clean_target.cmake
cd /tmp/llvm@5-20180313-32135-1yumi5f/lib/DebugInfo/PDB && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.10.2/bin/cmake -E cmake_link_script CMakeFiles/LLVMDebugInfoPDB.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/bin/ar qc ../../libLLVMDebugInfoPDB.a  CMakeFiles/LLVMDebugInfoPDB.dir/GenericError.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/IPDBSourceFile.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDB.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBContext.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBExtras.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBInterfaceAnchors.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbol.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolAnnotation.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolBlock.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolCompiland.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolCompilandDetails.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolCompilandEnv.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolCustom.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolData.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolExe.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolFunc.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolFuncDebugEnd.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolFuncDebugStart.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolLabel.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolPublicSymbol.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolThunk.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeArray.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeBaseClass.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeBuiltin.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeCustom.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeDimension.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeEnum.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeFriend.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeFunctionArg.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeFunctionSig.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeManaged.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypePointer.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeTypedef.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeUDT.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeVTable.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolTypeVTableShape.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolUnknown.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymbolUsingNamespace.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/PDBSymDumper.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/UDTLayout.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/DbiModuleDescriptor.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/DbiModuleDescriptorBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/DbiModuleList.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/DbiStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/DbiStreamBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/EnumTables.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/GlobalsStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/GSI.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/Hash.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/HashTable.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/InfoStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/InfoStreamBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/ModuleDebugStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/NativeBuiltinSymbol.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/NativeCompilandSymbol.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/NativeEnumModules.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/NativeExeSymbol.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/NativeRawSymbol.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/NamedStreamMap.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/NativeSession.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/PDBFile.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/PDBFileBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/PDBStringTable.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/PDBStringTableBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/PublicsStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/PublicsStreamBuilder.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/RawError.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/SymbolStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/TpiHashing.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/TpiStream.cpp.o CMakeFiles/LLVMDebugInfoPDB.dir/Native/TpiStreamBuilder.cpp.o
/home/linuxbrew/.linuxbrew/bin/ranlib ../../libLLVMDebugInfoPDB.a
make[2]: Leaving directory '/tmp/llvm@5-20180313-32135-1yumi5f'
[ 15%] Built target LLVMDebugInfoPDB
make[1]: Leaving directory '/tmp/llvm@5-20180313-32135-1yumi5f'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sjackman** [comment] 2018-03-13 23:42
Duplicate of https://github.com/Linuxbrew/homebrew-core/pull/6598

**Closed as completed by sjackman** 2018-03-13 23:42 UTC
Labels: duplicate
