### ISSUE TITLE
gcc@4.8

### ISSUE THREAD

**Issue by rojinsafavi** [Linuxbrew/brew#265] opened 2017-02-14 18:48 UTC
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [y ] Ran `brew update` and retried your prior step?
- [y ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

I would like to install gcc48 instead go gcc5

$ brew install gcc48
==> Installing dependencies for gcc@4.8: gmp@4, mpfr@2, libmpc@0.8, isl@0.12, cloog, cctools-headers, cctools
==> Installing gcc@4.8 dependency: gmp@4
==> Downloading https://ftpmirror.gnu.org/gmp/gmp-4.3.2.tar.bz2
Already downloaded: /soe/rojinsafavi/.cache/Homebrew/gmp@4-4.3.2.tar.bz2
==> Patching
patching file gmp-h.in
==> ./configure --prefix=/soe/rojinsafavi/.linuxbrew/Cellar/gmp@4/4.3.2 --enable-cxx --build=x86_64-apple-darwin
Last 15 lines from /soe/rojinsafavi/.cache/Homebrew/Logs/gmp@4/01.configure:

checking build system type... x86_64-apple-darwin
checking host system type... x86_64-apple-darwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking whether /soe/rojinsafavi/.linuxbrew/bin/gcc-5 is gcc... yes
checking compiler /soe/rojinsafavi/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -m64 -isystem/soe/rojinsafavi/.linuxbrew/include... no
checking ABI=32
checking whether /soe/rojinsafavi/.linuxbrew/bin/gcc-5 is gcc... yes
checking compiler /soe/rojinsafavi/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -m64 -isystem/soe/rojinsafavi/.linuxbrew/include... no
configure: error: could not find a working compiler, see config.log for details

Any hint?

Regards,
Rojin

**Comment by sjackman** [comment] 2017-02-15 19:15
Duplicate of #264

**Closed as completed by sjackman** 2017-02-15 19:15 UTC
Labels: duplicate
