### ISSUE TITLE
atk doesn't find python 2.7 folder

### ISSUE THREAD

**Issue by jney** [Linuxbrew/brew#645] opened 2018-03-13 21:42 UTC
```
==> Downloading https://download.gnome.org/sources/atk/2.28/atk-2.28.1.tar.xz
Already downloaded: /home/jney/.cache/Homebrew/atk-2.28.1.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/atk/2.28.1 --enable-introspection=yes
==> make
Last 15 lines from /home/jney/.cache/Homebrew/Logs/atk/02.make:
  CC       atk-enum-types.lo
  CCLD     libatk-1.0.la
  GISCAN   Atk-1.0.gir
/usr/bin/env: ‘/home/linuxbrew/.linuxbrew/opt/python/bin/python2.7’: No such file or directory
/home/linuxbrew/.linuxbrew/Cellar/gobject-introspection/1.54.1_1/share/gobject-introspection-1.0/Makefile.introspection:159: recipe for target 'Atk-1.0.gir' failed
make[3]: *** [Atk-1.0.gir] Error 127
make[3]: Leaving directory '/tmp/atk-20180313-13012-adj3ka/atk-2.28.1/atk'
Makefile:688: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/atk-20180313-13012-adj3ka/atk-2.28.1/atk'
Makefile:537: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/atk-20180313-13012-adj3ka/atk-2.28.1'
Makefile:444: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sjackman** [comment] 2018-03-13 23:41
Duplicate of https://github.com/Linuxbrew/homebrew-core/pull/6575

**Closed as completed by sjackman** 2018-03-13 23:41 UTC
